version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_api
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
volumes:
  pgdata: